sonar.projectKey=ServeAt
sonar.projectName=ServeAt
sonar.sourceEncoding=UTF-8
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.coverage.exclusions=src/main/java/com/serveat/core/util/DataInitializer.java