name: Java CI with Maven + SonarCloud

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Java 21 (Temurin) + Maven cache
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: maven

      - name: Build and analyze with SonarCloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mvn -B clean verify \
            org.sonarsource.scanner.maven:sonar-maven-plugin:5.5.0.6356:sonar \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.projectKey=joseob97_IW2025-2026-PROYECTO-ServEat \
            -Dsonar.organization=iw2025-2026-proyecto-serveat \
            -Dsonar.token=$SONAR_TOKEN
