name: SonarCloud analysis

on:
  push:
    branches: [ "main", "feature/**" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: maven

      - name: Build + SonarCloud (Maven)
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn -B -DskipTests verify sonar:sonar \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.projectKey=joseob97_IW2025-2026-PROYECTO-ServEat \
            -Dsonar.organization=iw2025-2026-proyecto-serveat \
            -Dsonar.token=$SONAR_TOKEN
